id: 5427c80a42da4f9ebb71201dda3b857f
initial_creation_type: ocr
source_metadata:
  volumes:
    96f6fdcecf254d838868fb98bb62528f:
      base_file: v105.txt
      image_group_id: I1PD95951
      title: ''
      total_pages: 1054
      volume_number: 106
